python train.py --dataset regdb --gpu 0 --trial 1
python train.py --dataset regdb --gpu 0 --trial 2
python train.py --dataset regdb --gpu 0 --trial 3
python train.py --dataset regdb --gpu 0 --trial 4
python train.py --dataset regdb --gpu 0 --trial 5
python train.py --dataset regdb --gpu 0 --trial 6
python train.py --dataset regdb --gpu 0 --trial 7
python train.py --dataset regdb --gpu 0 --trial 8
python train.py --dataset regdb --gpu 0 --trial 9
python train.py --dataset regdb --gpu 0 --trial 10
